<a href="https://colab.research.google.com/github/Briyad37/Rwanda-youth-employment-skills-gap/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import needed libraries

In [ ]:
import pandas as pd
import os

# Connect to Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path ="/content/drive/MyDrive/Rwanda-youth-employment-skills-gap"
file_path = os.path.join(path,"labour_force_by_youth_adult.csv")

In [ ]:
dictionary_path = os.path.join(path,"dictionary_labour_force_by_youth_adult.csv")

In [ ]:
cleaned_path =  os.path.join(path,"cleaned_labour_force_by_youth_adult.csv")

# Read the file

In [ ]:
df = pd.read_csv(file_path, na_values = ["NA","N/A","",".","..","-",","])

In [ ]:
df.tail(3)

,youth_adult,year,quarter,employment_to_population_ratio,labour_force_participation_rate,lu1_unemployment_rate,lu2_combined_rate_of_unemployment_and_time_related_underempl,lu3_combined_rate_of_unemployment_and_potential_labour_force,lu4_composite_measure_of_labour_underutilization,median_monthly_earnings_at_main_job,neet_rate_youth_not_in_employment_nor_currently_in_education,out_of_labour_force_inactivity_rate,time_related_underemployment_rate
53,Youth (Age:16-30 years),2025,Q2,49.054327,58.012828,15.442275,45.922881,33.008428,57.156945,39000.0,24.642198,41.987172,36.047098
54,Youth (Age:16-30 years),2025,Q3,56.646385,67.070890,15.542518,45.837596,34.233406,57.824022,39000.0,25.593357,32.929110,35.870212
55,Youth (Age:16-30 years),2025,Q4,52.218215,60.807359,14.125172,45.674393,32.228677,57.126921,39000.0,24.889686,39.192641,36.738612

# Cleaning the Data

01.Correct youth_adult column values

In [ ]:
df["youth_adult"] = df["youth_adult"].str.lower().str.strip()

df.loc[df["youth_adult"].str.contains("youth",na=False), "youth_adult"]= "Youth"
df.loc[df["youth_adult"].str.contains("adult", na=False), "youth_adult"]= "Adult"

df.rename(columns={"youth_adult":"age_group"}, inplace=True)

02.Handling missing values

In [ ]:
#check numer of missing values from each column.
df.isna().sum()

age_group                                                        0
year                                                             0
quarter                                                          0
employment_to_population_ratio                                   0
labour_force_participation_rate                                  0
lu1_unemployment_rate                                            0
lu2_combined_rate_of_unemployment_and_time_related_underempl     0
lu3_combined_rate_of_unemployment_and_potential_labour_force     0
lu4_composite_measure_of_labour_underutilization                 2
median_monthly_earnings_at_main_job                              2
neet_rate_youth_not_in_employment_nor_currently_in_education    29
out_of_labour_force_inactivity_rate                              0
time_related_underemployment_rate                                0
dtype: int64

In [ ]:
#Check missing percentage from each column
df.isna().mean()*100

age_group                                                        0.000000
year                                                             0.000000
quarter                                                          0.000000
employment_to_population_ratio                                   0.000000
labour_force_participation_rate                                  0.000000
lu1_unemployment_rate                                            0.000000
lu2_combined_rate_of_unemployment_and_time_related_underempl     0.000000
lu3_combined_rate_of_unemployment_and_potential_labour_force     0.000000
lu4_composite_measure_of_labour_underutilization                 3.571429
median_monthly_earnings_at_main_job                              3.571429
neet_rate_youth_not_in_employment_nor_currently_in_education    51.785714
out_of_labour_force_inactivity_rate                              0.000000
time_related_underemployment_rate                                0.000000
dtype: float64

03. Cleaning column names

In [ ]:
#We make column names lower case, remove spaces before and after and replace blank spaces with  underscores
df.columns=(
    df.columns
    .str.lower()
    .str.strip()
)

In [ ]:
df.rename(columns={
    "lu2_combined_rate_of_unemployment_and_time_related_underempl":"lu2_unemployment_underemployment_rate",
    "lu3_combined_rate_of_unemployment_and_potential_labour_force":"lu3_unemployment_potential_lf_rate",
    "lu4_composite_measure_of_labour_underutilization":"lu4_labour_underutilization_rate",
    "neet_rate_youth_not_in_employment_nor_currently_in_education":"youth_neet_rate",
    "labour_force_participation_rate":"lf_participation_rate",
    "median_monthly_earnings_at_main_job":"median_monthly_earnings",
    "out_of_labour_force_inactivity_rate":"out_of_lf_inactivity_rate",
    "time_related_underemployment_rate":"time_underemployment_rate"

},inplace=True, errors="raise")

04.Clean data types of columns' values

In [ ]:
#We check data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   age_group                              56 non-null     object
 1   year                                   56 non-null     int64
 2   quarter                                56 non-null     object
 3   employment_to_population_ratio         56 non-null     float64
 4   lf_participation_rate                  56 non-null     float64
 5   lu1_unemployment_rate                  56 non-null     float64
 6   lu2_unemployment_underemployment_rate  56 non-null     float64
 7   lu3_unemployment_potential_lf_rate     56 non-null     float64
 8   lu4_labour_underutilization_rate       54 non-null     float64
 9   median_monthly_earnings                54 non-null     float64
 10  youth_neet_rate                        27 non-null     float64
 11  out_of_lf_inactivity_rate              56 non-null     float64
 12  time_underemployment_rate              56 non-null     float64
dtypes: float64(10), int64(1), object(2)
memory usage: 5.8+ KB

as we can see from above results every column has the right data type!

)5.Removing duplicate rows

In [ ]:
#first, we check number of duplicaed rows
df.duplicated().sum()

np.int64(0)

In [ ]:
#then we see the dupliated rows are which ones
df[df.duplicated()]

Empty DataFrame
Columns: [age_group, year, quarter, employment_to_population_ratio, lf_participation_rate, lu1_unemployment_rate, lu2_unemployment_underemployment_rate, lu3_unemployment_potential_lf_rate, lu4_labour_underutilization_rate, median_monthly_earnings, youth_neet_rate, out_of_lf_inactivity_rate, time_underemployment_rate]
Index: []

We see from the above that we do not have duplicated rows!

In [ ]:
df

,age_group,year,quarter,employment_to_population_ratio,lf_participation_rate,lu1_unemployment_rate,lu2_unemployment_underemployment_rate,lu3_unemployment_potential_lf_rate,lu4_labour_underutilization_rate,median_monthly_earnings,youth_neet_rate,out_of_lf_inactivity_rate,time_underemployment_rate
0,Adult,2019,Q1,48.331897,54.232306,10.879878,35.645545,36.495948,54.143143,24000.0,NaN,45.767694,27.789086
1,Adult,2019,Q2,48.929103,55.945526,12.541526,35.608738,36.854824,53.509393,26000.0,NaN,44.054474,26.375046
2,Adult,2019,Q3,47.259101,53.953333,12.407450,35.794088,38.638449,55.021582,26000.0,NaN,46.046667,26.699346
3,Adult,2019,Q4,49.805675,56.691319,12.145853,34.915767,35.788924,52.431060,26000.0,NaN,43.308681,25.917859
4,Adult,2020,Q1,51.932353,57.598108,9.836704,37.669036,34.140010,54.470202,26000.0,NaN,42.401892,30.868805
5,Adult,2020,Q2,46.757345,56.799070,17.679382,0.000000,17.679382,NaN,NaN,NaN,43.200930,0.000000
6,Adult,2020,Q3,51.009718,57.981579,12.024267,35.642713,35.681362,52.948695,26000.0,NaN,42.018421,26.846546
7,Adult,2020,Q4,48.202467,57.955786,16.828896,42.843337,37.933932,57.347093,26000.0,NaN,42.044214,31.278220
8,Adult,2021,Q1,46.979930,54.422834,13.676068,40.768066,36.134412,56.178059,26000.0,NaN,45.577166,31.384111
9,Adult,2021,Q2,44.299872,55.350819,19.965281,43.851995,40.402504,58.189639,26000.0,NaN,44.649181,29.845440
10,Adult,2021,Q3,46.117575,54.215511,14.936566,39.925178,37.666867,55.978125,26000.0,NaN,45.784489,29.376444
11,Adult,2021,Q4,51.780039,64.189601,19.332667,43.907382,33.222625,53.565865,26000.0,NaN,35.810399,30.464271
12,Adult,2022,Q1,50.888925,58.543875,13.075578,36.606541,29.972434,48.929317,26000.0,NaN,41.456125,27.070601
13,Adult,2022,Q2,47.506133,58.927622,19.382234,46.320151,37.135064,58.140986,26000.0,NaN,41.072378,33.414369
14,Adult,2022,Q3,50.697074,59.612480,14.955603,42.314242,33.268516,54.735922,26000.0,NaN,40.387520,32.169832
15,Adult,2022,Q4,49.667131,62.498815,20.531083,46.585573,35.811057,56.855891,26000.0,NaN,37.501185,32.785762
16,Adult,2023,Q1,51.290271,60.416858,15.106027,38.688799,33.784561,52.178607,26000.0,NaN,39.583142,27.779089
17,Adult,2023,Q2,54.505710,63.182736,13.733222,38.612621,30.632323,50.638010,26000.0,NaN,36.817264,28.840070
18,Adult,2023,Q3,51.077346,60.708685,15.864845,40.250977,34.584818,53.545064,31200.0,NaN,39.291315,28.984474
19,Adult,2023,Q4,53.215540,62.135633,14.355842,40.547520,32.467788,53.120474,31200.0,NaN,37.864367,30.581979
20,Adult,2024,Q1,57.396890,64.006172,10.326008,34.705117,27.774081,47.409691,31200.0,NaN,35.993828,27.186376
21,Adult,2024,Q2,55.829437,65.011309,14.123501,41.367185,31.286396,53.085279,39000.0,NaN,34.988691,31.724261
22,Adult,2024,Q3,55.615383,63.452551,12.351227,43.430018,32.635915,56.522095,39000.0,NaN,36.547449,35.458330
23,Adult,2024,Q4,58.385194,66.561045,12.283236,42.549296,29.489720,53.818802,39000.0,NaN,33.438955,34.504306
24,Adult,2025,Q1,60.093482,66.428309,9.536336,41.156177,27.952949,53.135615,39000.0,NaN,33.571691,34.953085
25,Adult,2025,Q2,57.438031,65.331876,12.082685,44.861485,31.427389,56.993774,39000.0,NaN,34.668124,37.283668
26,Adult,2025,Q3,57.335072,64.906578,11.665238,42.622986,31.993287,55.826879,39000.0,NaN,35.093422,35.045940
27,Adult,2025,Q4,60.020069,66.680305,9.988309,43.686589,29.754620,56.052854,39000.0,NaN,33.319695,37.437670
28,Youth,2019,Q1,40.678899,50.404707,19.295437,43.880816,42.725815,60.173498,20800.0,34.387321,49.595293,30.463432
29,Youth,2019,Q2,41.795230,51.093980,18.199306,39.974693,41.502796,57.074782,20000.0,32.777859,48.906020,26.620051
30,Youth,2019,Q3,39.943685,50.287317,20.569068,42.446621,43.994097,59.419726,20800.0,35.700389,49.712683,27.542864
31,Youth,2019,Q4,42.604814,52.965666,19.561449,39.494480,42.742405,56.931092,20800.0,34.441827,47.034334,24.780445
32,Youth,2020,Q1,44.039746,53.239635,17.280150,45.787787,39.891074,60.606337,20800.0,34.170719,46.760365,34.462873
33,Youth,2020,Q2,38.857899,53.345008,27.157385,0.000000,27.157385,NaN,NaN,NaN,46.654992,0.000000
34,Youth,2020,Q3,46.398571,58.404582,20.556626,43.478219,43.843360,60.046091,26000.0,31.811045,41.595418,28.852744
35,Youth,2020,Q4,41.434095,54.926426,24.564372,50.131712,43.607599,62.720633,26000.0,34.737038,45.073574,33.892924
36,Youth,2021,Q1,36.088311,46.073852,21.672904,47.886871,44.145485,62.838485,20800.0,34.378189,53.926148,33.467303
37,Youth,2021,Q2,36.546751,50.746832,27.982203,52.107947,43.317319,62.305846,24000.0,37.197243,49.253168,33.499698
38,Youth,2021,Q3,34.928617,46.904930,25.533165,48.908596,49.274192,65.197222,26000.0,37.713198,53.095070,31.390391
39,Youth,2021,Q4,40.243802,57.298730,29.764932,52.044587,42.787716,60.936341,26000.0,33.027874,42.701270,31.721554
40,Youth,2022,Q1,38.839495,49.498349,21.533756,45.500969,39.925364,58.274930,24000.0,31.603079,50.501651,30.544616
41,Youth,2022,Q2,34.903654,48.717008,28.354275,50.526262,45.923451,62.658358,26000.0,36.230231,51.282992,30.946700
42,Youth,2022,Q3,40.920430,52.858445,22.584879,50.569144,42.435380,63.244022,26000.0,32.893658,47.141555,36.148319
43,Youth,2022,Q4,37.961846,53.986644,29.682893,51.930361,44.278414,61.908038,26000.0,36.026643,46.013356,31.638769
44,Youth,2023,Q1,42.867232,53.876057,20.433614,43.868461,39.567829,57.367037,26000.0,33.184498,46.123943,29.453201
45,Youth,2023,Q2,42.905794,54.684181,21.538929,44.632703,38.951449,56.920123,26000.0,33.650443,45.315819,29.433416
46,Youth,2023,Q3,46.395188,58.708961,20.974266,45.566440,40.223506,58.825471,30000.0,33.190718,41.291039,31.119197
47,Youth,2023,Q4,45.684583,57.326790,20.308493,44.174476,36.687589,55.648366,26000.0,31.464717,42.673210,29.947963
48,Youth,2024,Q1,47.735240,57.241346,16.607062,41.116880,32.813395,52.560049,31200.0,28.421623,42.758654,29.390760
49,Youth,2024,Q2,47.208410,59.380503,20.498468,45.601956,34.435959,55.138530,31200.0,28.994632,40.619497,31.576106
50,Youth,2024,Q3,52.623455,64.828622,18.826819,47.913523,37.466539,59.874090,39000.0,29.131187,35.171378,35.832898
51,Youth,2024,Q4,49.913791,60.859025,17.984570,46.594370,33.368405,56.611794,31200.0,27.258419,39.140975,34.883435
52,Youth,2025,Q1,50.517775,58.450696,13.571988,43.869068,29.889837,54.466744,31500.0,23.022515,41.549304,35.054700
53,Youth,2025,Q2,49.054327,58.012828,15.442275,45.922881,33.008428,57.156945,39000.0,24.642198,41.987172,36.047098
54,Youth,2025,Q3,56.646385,67.070890,15.542518,45.837596,34.233406,57.824022,39000.0,25.593357,32.929110,35.870212
55,Youth,2025,Q4,52.218215,60.807359,14.125172,45.674393,32.228677,57.126921,39000.0,24.889686,39.192641,36.738612

I can say that the Table is now clean and It's time to export a final cleaned dataset

Create a data Dictionary

In [ ]:
dictionary_df = pd.DataFrame({
    "column_names":df.columns,
"data_type":df.dtypes,
"description":[
    "Age category: Youth (Age: 16-30 years) or Adult (Age: 31 and over)",
    "Survey year (2019 to 2025)",
    "Survey quarter (Q1, Q2, Q3, Q4)",
    "Employment-to-population ratio for this age category (%)",
    "Participation rate for this age category (%)",
    "Unemployment rate for this age category (%)",
    "Combined unemployment and underemployment rate (%)",
    "Combined unemployment and potential labour force rate (%)",
    "Composite labour underutilization (%)",
    "Median monthly earnings at main job (RWF)",
    "Youth NEET rate (%)",
    "Inactivity rate (%)",
    "Time-related underemployment rate (%)"
]
})

EXPORTING Cleaned Dataset!

In [ ]:
df.to_csv(cleaned_path,index=False, encoding="utf-8-sig")

In [ ]:
dictionary_df.to_csv(dictionary_path,index=False, encoding="utf-8-sig")